const GLOBAL_FETCH_START = 'GLOBAL_FETCH_START';
const GLOBAL_FETCH_END = 'GLOBAL_FETCH_END';
const GLOBAL_SET_STATE = 'GLOBAL_SET_STATE';
const GLOBAL_RESET_STATE = 'GLOBAL_RESET_STATE';


export default {
  GLOBAL_FETCH_START,
  GLOBAL_FETCH_END,
  GLOBAL_SET_STATE,
  GLOBAL_RESET_STATE,
};
