const USER_FETCH_START = 'USER_FETCH_START';
const USER_FETCH_END = 'USER_FETCH_END';
const USER_SET_STATE = 'USER_SET_STATE';
const USER_RESET_STATE = 'USER_RESET_STATE';

const GLOBAL_FETCH_START = 'GLOBAL_FETCH_START';
const GLOBAL_FETCH_END = 'GLOBAL_FETCH_END';
const GLOBAL_SET_STATE = 'GLOBAL_SET_STATE';
const GLOBAL_RESET_STATE = 'GLOBAL_RESET_STATE';


export default {
  USER_FETCH_START,
  USER_FETCH_END,
  USER_SET_STATE,
  USER_RESET_STATE,
  GLOBAL_FETCH_START,
  GLOBAL_FETCH_END,
  GLOBAL_SET_STATE,
  GLOBAL_RESET_STATE,
};
